import { useCallback, useEffect, useRef, useState } from 'react';
import { Minus, Plus, RotateCcw } from 'lucide-react';

type Props = {
  svg: string;
  diagramId: string;
  selected: string | null;
  onSelect: (name: string | null) => void;
};

const MIN = 0.2;
const MAX = 6;
const STEP = 40;

export function DiagramCanvas({ svg, diagramId, selected, onSelect }: Props) {
  const hostRef = useRef<HTMLDivElement>(null);
  const [t, setT] = useState({ x: 0, y: 0, k: 1 });
  const drag = useRef<{ x: number; y: number; ox: number; oy: number } | null>(null);

  // Reflect selection onto the injected markup (it lives outside React's tree).
  useEffect(() => {
    const host = hostRef.current;
    if (!host) return;
    host.querySelectorAll('g.node').forEach((g) => {
      const name = g.querySelector('title')?.textContent ?? '';
      if (name === selected) g.setAttribute('data-selected', 'true');
      else g.removeAttribute('data-selected');
    });
  }, [selected, svg]);

  // Make nodes focusable so the diagram is keyboard-navigable.
  useEffect(() => {
    hostRef.current?.querySelectorAll('g.node').forEach((g) => {
      g.setAttribute('tabindex', '0');
      g.setAttribute('role', 'button');
      const name = g.querySelector('title')?.textContent ?? '';
      g.setAttribute('aria-label', `${name} — open details`);
    });
  }, [svg]);

  const pick = useCallback(
    (target: EventTarget | null) => {
      const g = (target as Element | null)?.closest?.('g.node');
      const name = g?.querySelector('title')?.textContent ?? null;
      onSelect(name);
    },
    [onSelect],
  );

  const zoomBy = useCallback((f: number) => {
    setT((p) => ({ ...p, k: Math.min(MAX, Math.max(MIN, p.k * f)) }));
  }, []);

  const onWheel = useCallback((e: React.WheelEvent) => {
    if (!e.ctrlKey && !e.metaKey) return; // let the page scroll normally
    e.preventDefault();
    setT((p) => ({ ...p, k: Math.min(MAX, Math.max(MIN, p.k * (e.deltaY < 0 ? 1.1 : 1 / 1.1))) }));
  }, []);

  const onPointerDown = (e: React.PointerEvent) => {
    if (e.button !== 0) return;
    drag.current = { x: e.clientX, y: e.clientY, ox: t.x, oy: t.y };
    (e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId);
  };
  const onPointerMove = (e: React.PointerEvent) => {
    const d = drag.current;
    if (!d) return;
    setT((p) => ({ ...p, x: d.ox + (e.clientX - d.x), y: d.oy + (e.clientY - d.y) }));
  };
  const onPointerUp = () => {
    drag.current = null;
  };

  const onKeyDown = (e: React.KeyboardEvent) => {
    const map: Record<string, [number, number]> = {
      ArrowRight: [-STEP, 0],
      ArrowLeft: [STEP, 0],
      ArrowDown: [0, -STEP],
      ArrowUp: [0, STEP],
    };
    const d = map[e.key];
    if (d) {
      e.preventDefault();
      setT((p) => ({ ...p, x: p.x + d[0], y: p.y + d[1] }));
      return;
    }
    if (e.key === '+' || e.key === '=') {
      e.preventDefault();
      zoomBy(1.2);
    }
    if (e.key === '-') {
      e.preventDefault();
      zoomBy(1 / 1.2);
    }
    if (e.key === '0') {
      e.preventDefault();
      setT({ x: 0, y: 0, k: 1 });
    }
    if (e.key === 'Escape') onSelect(null);
  };

  return (
    <div className="arch-canvas">
      <div className="arch-tools">
        <button type="button" className="arch-btn" aria-label="Zoom in" onClick={() => zoomBy(1.2)}>
          <Plus size={13} aria-hidden />
        </button>
        <button
          type="button"
          className="arch-btn"
          aria-label="Zoom out"
          onClick={() => zoomBy(1 / 1.2)}
        >
          <Minus size={13} aria-hidden />
        </button>
        <button
          type="button"
          className="arch-btn"
          aria-label="Reset view"
          onClick={() => setT({ x: 0, y: 0, k: 1 })}
        >
          <RotateCcw size={13} aria-hidden />
        </button>
        <span className="arch-zoom">{Math.round(t.k * 100)}%</span>
      </div>
      <div
        className="arch-viewport"
        tabIndex={0}
        role="application"
        aria-label={`${diagramId} diagram — arrow keys pan, plus and minus zoom, 0 resets`}
        onWheel={onWheel}
        onPointerDown={onPointerDown}
        onPointerMove={onPointerMove}
        onPointerUp={onPointerUp}
        onKeyDown={onKeyDown}
        onClick={(e) => pick(e.target)}
      >
        <div
          className="arch-stage"
          ref={hostRef}
          style={{ transform: `translate(${t.x}px, ${t.y}px) scale(${t.k})` }}
          /* Build-time authored asset generated by tools/architecture/build_diagrams.py,
             never user input. */
          dangerouslySetInnerHTML={{ __html: svg }}
        />
      </div>
    </div>
  );
}
