/**
 * The course's offline-signing public key, hex-encoded ed25519 (32 bytes => 64 hex chars).
 * In production this is the real course key; here it is a dev keypair generated by
 * tools/sign-cs61a-manifest.ts. The private key never enters the repo.
 */
export const COURSE_PUBLIC_KEY_HEX =
  '46f91d5902c53816110b05ddedd2b8caa95b452d51e696f5327b52bf90bf4838';
